<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-05-07T11:48:01Z" name="Default suite" finished-at="2022-05-07T11:48:29Z" duration-ms="27735">
    <groups>
    </groups>
    <test started-at="2022-05-07T11:48:01Z" name="Default test" finished-at="2022-05-07T11:48:29Z" duration-ms="27735">
      <class name="Test.TestModuleUI">
        <test-method is-config="true" signature="init()[pri:0, instance:Test.TestModuleUI@6f4a47c7]" started-at="2022-05-07T11:48:01Z" name="init" finished-at="2022-05-07T11:48:04Z" duration-ms="2959" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="TC_001()[pri:0, instance:Test.TestModuleUI@6f4a47c7]" started-at="2022-05-07T11:48:04Z" name="TC_001" description="Verify fields in login screen" finished-at="2022-05-07T11:48:28Z" duration-ms="24039" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Release Date don't match expected [2022-01-07] but found [2021-12-17]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Release Date don't match expected [2022-01-07] but found [2021-12-17]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at Test.TestModuleUI.TC_001(TestModuleUI.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_001 -->
        <test-method is-config="true" signature="quitBrowser()[pri:0, instance:Test.TestModuleUI@6f4a47c7]" started-at="2022-05-07T11:48:28Z" name="quitBrowser" finished-at="2022-05-07T11:48:29Z" duration-ms="715" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
      </class> <!-- Test.TestModuleUI -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
